### ISSUE TITLE
The flipper does not beep

### ISSUE THREAD

**Issue by gotofuckinghell** [Th3Un1q3/flipp_pomodoro#260]
Flipper does not beep or blink for the last 5 seconds of the timer, and for a pause. (as it was implemented in YouTube videos) Please add this

**Comment by gotofuckinghell** [comment]
Сорри я не совсем разобрался, какой аппки ды дев (последний анлишед ссылается на тебя), ФлипПомодорро или Помодорро Флиппер. Эни вей , настроек там не видно, добавь пищание и илюминацию пожалуйста

**Comment by Th3Un1q3** [comment]
Hi @gotofuckinghell!

In the Flipp Pomodoro app, when you switch stages, temporary lighting, vibrations, a ringtone, and LED blinking come into play.Vibration and ringtone settings are actually configured in a separate menu, not within the app itself. You can find more detailed information [here](https://github.com/Th3Un1q3/flipp_pomodoro/discussions/54#discussioncomment-5893009).

Thanks a lot for sharing your thoughts. If this doesn't resolve the issue, could you let me know your firmware version?

**Comment by gotofuckinghell** [comment]
I don't know if you can hear me or not, lol, but the app without notification is not realistic to use(tested 5 laps, I can't hear flipper), it has to be either wedged into the music/noise playing on the pc or made to be heard/noticed in the headphones.The app by the way has no loops, and each time a new circle has to be pressed independently

The firmware is the latest unleashed, the application is from his package.

**Comment by Th3Un1q3** [comment]
Hello there,

I appreciate your feedback and your interest in Flipp Pomodoro. It seems there might be a bit of confusion here. The issues you've mentioned regarding beeping and blinking during the timer's last 5 seconds and the pause are actually not applicable to my app, Flipp Pomodoro. I have verified this from the latest firmware package, version 62e, where both the looping and sound features are indeed present.

I understand your concerns about notifications and audibility. Flipp Pomodoro is designed to accommodate various preferences and environments, but it appears you might be referring to a different application. I do take your point about the importance of notifications seriously.

If you'd like to modify the notification pattern to better suit your needs, you can certainly explore the source code available at https://github.com/Th3Un1q3/flipp_pomodoro/blob/master/flipp_pomodoro/helpers/notifications.c. Feel free to build the app with your desired changes or even submit a pull request. I'd be more than happy to review your modifications and consider publishing them for the wider community.

I'm sorry, but I wasn't able to understand which videos you were referencing since no link was provided. If you could provide more context, I'd be glad to look into it further.

While I understand your suggestions, I currently don't have any plans to make changes to the app's functionality. However, I'm here to assist if you have any questions or concerns about the existing features. Your feedback is valuable, and I'll keep it in mind as I continue to develop and maintain Flipp Pomodoro.

Thank you for using Flipp Pomodoro, and please let me know if there's anything else I can help you with!
