### ISSUE TITLE
Flipper speaking is buggy

### ISSUE THREAD

**Issue by DefinetlyNotAI** [Th3Un1q3/flipp_pomodoro#350]
When you speak with the flipper using Middle Button, the speech is weird and inconsistant... it quickly loops back and doesnt seem ok... and moves very fast...

Maybe remove the loop feature? Or make it wait a certian period before removing/looping his speech, or waits until another button press is made?

**Comment by Th3Un1q3** [comment]
Oh, your right. It makes sense to make it time based instead of FPS based.

**Comment by DefinetlyNotAI** [comment]
But I was a total accident to discover the feature... maybe advertise it??

**Comment by Th3Un1q3** [comment]
I've identified an issue where Flipper app frame rate (FPS) varies depending on where you launch it from. Launching from the "Favorites" menu seems stable, but starting from the "All Apps" menu causes text flickering. Due to time limitations, a fix can't be implemented right now. This issue will remain open until I have a chance to address it myself or someone from the community volunteers to help. Thanks for reporting it!

**Comment by DefinetlyNotAI** [comment]
You are correct, it seems that if i have opened it from the fav tab, its stable, if i open it from the apps its flickerish and from the browser 50/50

**Comment by DefinetlyNotAI** [comment]
Hey, should i work on it then?

(Or attempt to??)
